pluginManagement {
    repositories {
        gradlePluginPortal()
        maven {
            url = 'https://maven.minecraftforge.net/'
            allowInsecureProtocol = true
        }
        maven { url = 'https://maven.parchmentmc.org' }
    }
}

rootProject.name = 'infected-ore-info'
