modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="jade"
type="required"
versionRange="${jade_version_range}"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="born_in_chaos_v1"
type="required"
reason="This compatibility mod only applies to Born in Chaos blocks."
versionRange="${born_in_chaos_version_range}"
ordering="AFTER"
side="BOTH"
